CREATE TABLE IF NOT EXISTS bandas (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    lore TEXT,
    imagem_url TEXT
);

CREATE TABLE IF NOT EXISTS albuns (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    ano_lancamento INT,
    id_banda INT REFERENCES bandas(id) ON DELETE CASCADE,
    imagem_url TEXT
);

CREATE TABLE IF NOT EXISTS musicas (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(100) NOT NULL,
    ano_lancamento INT,
    loreMsc TEXT,
    id_banda INT REFERENCES bandas(id) ON DELETE CASCADE,
    id_album INT REFERENCES albuns(id) ON DELETE SET NULL
);
