server:
    port: 8080

spring:
    datasource:
        platform: postgres
        url: jdbc:postgresql://localhost:5432/btldb
        username: postgres
        password: 123
        driverClassName: org.postgresql.Driver
        initialize: true

    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres
    