server:
  port: 8080
  error:
    whitelabel:
      enabled: true
    include-stacktrace: always

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
    initialize: true

  sql:
    init:
      schema-locations: classpath:/schema-postgresql.sql
      mode: always
      platform: postgres